### ISSUE TITLE
could not be complied. Try Rebuilding from Source manually

### ISSUE THREAD

**Issue by AnemoiThuellai** [getnamo/UnrealEnginePython#14]
I'm using plugin version: UnrealEnginePython_20190508_4_22_python36_embedded_win64
Unreal Engine: 4.21.1

I'm getting the following error when I add the plugin to the project directories:

Log file open, 05/22/19 17:03:16
LogWindows: Failed to load 'aqProf.dll' (GetLastError=126)
LogWindows: File 'aqProf.dll' does not exist
LogWindows: Failed to load 'VtuneApi.dll' (GetLastError=126)
LogWindows: File 'VtuneApi.dll' does not exist
LogWindows: Failed to load 'VtuneApi32e.dll' (GetLastError=126)
LogWindows: File 'VtuneApi32e.dll' does not exist
LogConsoleResponse: Display: Failed to find resolution value strings in scalability ini. Falling back to default.
LogInit: Display: Running engine for game: Project
LogPakFile: Registered encryption key '00000000000000000000000000000000': 0 pak files mounted, 0 remain pending
LogPlatformFile: Not using cached read wrapper
LogTaskGraph: Started task graph with 5 named threads and 23 total threads with 3 sets of task threads.
LogStats: Stats thread started at 0.269591
LogD3D11RHI: Loaded GFSDK_Aftermath_Lib.x64.dll
LogICUInternationalization: ICU TimeZone Detection - Raw Offset: -8:00, Platform Override: ''
LogPluginManager: Mounting plugin Paper2D
LogPluginManager: Mounting plugin AISupport
LogPluginManager: Mounting plugin LightPropagationVolume
LogPluginManager: Mounting plugin OpenCVLensDistortion
LogPluginManager: Mounting plugin ActorLayerUtilities
LogPluginManager: Mounting plugin CLionSourceCodeAccess
LogPluginManager: Mounting plugin CodeLiteSourceCodeAccess
LogPluginManager: Mounting plugin GitSourceControl
LogPluginManager: Mounting plugin KDevelopSourceCodeAccess
LogPluginManager: Mounting plugin NullSourceCodeAccess
LogPluginManager: Mounting plugin PerforceSourceControl
LogPluginManager: Mounting plugin SubversionSourceControl
LogPluginManager: Mounting plugin UObjectPlugin
LogPluginManager: Mounting plugin VisualStudioCodeSourceCodeAccess
LogPluginManager: Mounting plugin VisualStudioSourceCodeAccess
LogPluginManager: Mounting plugin XCodeSourceCodeAccess
LogPluginManager: Mounting plugin AssetManagerEditor
LogPluginManager: Mounting plugin CryptoKeys
LogPluginManager: Mounting plugin DataValidation
LogPluginManager: Mounting plugin EditorScriptingUtilities
LogPluginManager: Mounting plugin FacialAnimation
LogPluginManager: Mounting plugin GameplayTagsEditor
LogPluginManager: Mounting plugin MacGraphicsSwitching
LogPluginManager: Mounting plugin MeshEditor
LogPluginManager: Mounting plugin MobileLauncherProfileWizard
LogPluginManager: Mounting plugin PluginBrowser
LogPluginManager: Mounting plugin SpeedTreeImporter
LogPluginManager: Mounting plugin DatasmithContent
LogPluginManager: Mounting plugin VariantManagerContent
LogPluginManager: Mounting plugin AlembicImporter
LogPluginManager: Mounting plugin AppleImageUtils
LogPluginManager: Mounting plugin AppleVision
LogPluginManager: Mounting plugin BackChannel
LogPluginManager: Mounting plugin CharacterAI
LogPluginManager: Mounting plugin GeometryCache
LogPluginManager: Mounting plugin HTML5Networking
LogPluginManager: Mounting plugin ProxyLODPlugin
LogPluginManager: Mounting plugin MagicLeap
LogPluginManager: Mounting plugin MagicLeapMedia
LogPluginManager: Mounting plugin ParticleText
LogPluginManager: Mounting plugin AndroidMedia
LogPluginManager: Mounting plugin AudioCaptureTimecodeProvider
LogPluginManager: Mounting plugin AvfMedia
LogPluginManager: Mounting plugin ImgMedia
LogPluginManager: Mounting plugin LinearTimecode
LogPluginManager: Mounting plugin MediaCompositing
LogPluginManager: Mounting plugin MediaFrameworkUtilities
LogPluginManager: Mounting plugin MediaIOFramework
LogPluginManager: Mounting plugin MediaPlayerEditor
LogPluginManager: Mounting plugin TimecodeSynchronizer
LogPluginManager: Mounting plugin WebMMedia
LogPluginManager: Mounting plugin WmfMedia
LogPluginManager: Mounting plugin TcpMessaging
LogPluginManager: Mounting plugin UdpMessaging
LogPluginManager: Mounting plugin ActorSequence
LogPluginManager: Mounting plugin LevelSequenceEditor
LogPluginManager: Mounting plugin MatineeToLevelSequence
LogPluginManager: Mounting plugin NetcodeUnitTest
LogPluginManager: Mounting plugin NUTUnrealEngine4
LogPluginManager: Mounting plugin OnlineSubsystemGooglePlay
LogPluginManager: Mounting plugin OnlineSubsystemIOS
LogPluginManager: Mounting plugin OnlineFramework
LogPluginManager: Mounting plugin OnlineSubsystem
LogPluginManager: Mounting plugin OnlineSubsystemAmazon
LogPluginManager: Mounting plugin OnlineSubsystemFacebook
LogPluginManager: Mounting plugin OnlineSubsystemGoogle
LogPluginManager: Mounting plugin OnlineSubsystemNull
LogPluginManager: Mounting plugin OnlineSubsystemUtils
LogPluginManager: Mounting plugin LauncherChunkInstaller
LogPluginManager: Mounting plugin AndroidDeviceProfileSelector
LogPluginManager: Mounting plugin AndroidMoviePlayer
LogPluginManager: Mounting plugin AndroidPermission
LogPluginManager: Mounting plugin AppleMoviePlayer
LogPluginManager: Mounting plugin ArchVisCharacter
LogPluginManager: Mounting plugin AudioCapture
LogPluginManager: Mounting plugin CableComponent
LogPluginManager: Mounting plugin CustomMeshComponent
LogPluginManager: Mounting plugin EditableMesh
LogPluginManager: Mounting plugin ExampleDeviceProfileSelector
LogPluginManager: Mounting plugin Firebase
LogPluginManager: Mounting plugin GoogleCloudMessaging
LogPluginManager: Mounting plugin HTTPChunkInstaller
LogPluginManager: Mounting plugin IOSDeviceProfileSelector
LogPluginManager: Mounting plugin LinuxDeviceProfileSelector
LogPluginManager: Mounting plugin LocationServicesBPLibrary
LogPluginManager: Mounting plugin MobilePatchingUtils
LogPluginManager: Mounting plugin OculusVR
LogPluginManager: Mounting plugin PhysXVehicles
LogPluginManager: Mounting plugin ProceduralMeshComponent
LogPluginManager: Mounting plugin RuntimePhysXCooking
LogPluginManager: Mounting plugin SteamController
LogPluginManager: Mounting plugin SteamVR
LogPluginManager: Mounting plugin SunPosition
LogPluginManager: Mounting plugin WebBrowserWidget
LogPluginManager: Mounting plugin WebMMoviePlayer
LogPluginManager: Mounting plugin WindowsMoviePlayer
LogPluginManager: Mounting plugin UnrealEnginePython
LogPluginManager: Mounting plugin DatasmithCADImporter
LogPluginManager: Mounting plugin DatasmithFBXImporter
LogPluginManager: Mounting plugin DatasmithImporter
LogPluginManager: Mounting plugin MDLImporter
LogPluginManager: Mounting plugin StaticMeshEditorExtension
LogPluginManager: Mounting plugin VariantManager
LogStreaming: Display: Took  0.080s to configure plugins.
LogInit: Warning: Incompatible or missing module: UnrealEnginePython
LogInit: Warning: Incompatible or missing module: PythonAutomation
LogInit: Warning: Incompatible or missing module: PythonConsole
LogInit: Warning: Incompatible or missing module: PythonEditor
Running C:/Program Files/Epic Games/UE_4.21/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Win64 -Project="F:/Unreal_Projects/Project/Project.uproject" -TargetType=Editor -Progress -NoHotReloadFromIDE
Creating makefile for StudioEditor (no existing makefile)
Performing full C++ include scan (no include cache file)
Using Visual Studio 2017 14.16.27023 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023) and Windows 10.0.16299.0 SDK (C:\Program Files (x86)\Windows Kits\10).
@progress push 5%
Parsing headers for StudioEditor
  Running UnrealHeaderTool "F:\Unreal_Projects\Project\Project.uproject" "F:\Unreal_Projects\Project\Intermediate\Build\Win64\StudioEditor\Development\StudioEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
Reflection code generated for StudioEditor in 8.8026826 seconds
@progress pop
Writing dependency list to F:\Unreal_Projects\Project\Intermediate\DependencyLists\StudioEditor\Development\Win64\DependencyList.txt
No buildable actions for this target. Makefile will not be saved.
Target is up to date
Total build time: 17.12 seconds (NoActionsToExecute executor: 0.00 seconds)
LogInit: Warning: Still incompatible or missing module: UnrealEnginePython
LogInit: Warning: Still incompatible or missing module: PythonAutomation
LogInit: Warning: Still incompatible or missing module: PythonConsole
LogInit: Warning: Still incompatible or missing module: PythonEditor
LogExit: Preparing to exit.
LogModuleManager: Shutting down and abandoning module DesktopPlatform (38)
LogModuleManager: Shutting down and abandoning module AnimationModifiers (36)
LogModuleManager: Shutting down and abandoning module PropertyEditor (35)
LogModuleManager: Shutting down and abandoning module AudioEditor (32)
LogModuleManager: Shutting down and abandoning module TextureCompressor (30)
LogModuleManager: Shutting down and abandoning module ShaderCore (28)
LogModuleManager: Shutting down and abandoning module Landscape (26)
LogModuleManager: Shutting down and abandoning module SlateRHIRenderer (24)
LogModuleManager: Shutting down and abandoning module OpenGLDrv (22)
LogModuleManager: Shutting down and abandoning module D3D11RHI (20)
LogModuleManager: Shutting down and abandoning module AnimGraphRuntime (18)
LogModuleManager: Shutting down and abandoning module Renderer (16)
LogModuleManager: Shutting down and abandoning module Engine (14)
LogModuleManager: Shutting down and abandoning module CoreUObject (12)
LogModuleManager: Shutting down and abandoning module NetworkFile (10)
LogModuleManager: Shutting down and abandoning module CookedIterativeFile (8)
LogModuleManager: Shutting down and abandoning module StreamingFile (6)
LogModuleManager: Shutting down and abandoning module SandboxFile (4)
LogModuleManager: Shutting down and abandoning module PakFile (2)
LogExit: Exiting.
Log file closed, 05/22/19 17:05:06

**Comment by getnamo** [comment]
this plugin fork has a few changes which may make incompatible with parent fork releases, I recommend you use https://github.com/getnamo/UnrealEnginePython/releases/tag/1.8.0

**Comment by AnemoiThuellai** [comment]
That worked!  Thank you and thank you for this plug in!!!
