### ISSUE TITLE
No UE 4.22 binaries

### ISSUE THREAD

**Issue by LucasAstro** [getnamo/UnrealEnginePython#15]

**Comment by getnamo** [comment]
I don't think I uploaded separate binaries for 4.22 for this repo, but you can grab https://github.com/getnamo/tensorflow-ue4/releases/tag/0.13.0 and just extract the unrealenginepython plugin from it

**Comment by getnamo** [comment]
Wasn't a long process so I just went ahead and did it and updated the release: https://github.com/getnamo/UnrealEnginePython/releases/tag/1.9.0
